---
title: "Ges3000 Plots"
author: "Manuel Bohn"
date: "18 10 2018"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(ggthemes)
library(langcog)
library(lme4)
library(exactRankTests)
library(ggpubr)
```


```{r}
d1 <- read.csv(file="data/pt1_prod_up_comp.csv")%>%
  na.omit(prompts)

d2 <- read.csv(file="data/pt1_trans_3_4.csv") 

d6 <- read.csv(file="data/pt1_convergence.csv") %>% 
  mutate(Age = ifelse(age == "M48","4yo","6yo"))

d7 <- read.csv(file="data/pt1_drift_production.csv") %>% 
  mutate(Age = ifelse(age == "M48","4yo","6yo"))


d8 <- read.csv(file="data/pt1_drift_comprehension.csv") %>% 
  mutate(condition = ifelse(condition == "Abstract", "Abstract", "Iconic"))%>%
  mutate(condition = as.factor(condition))%>%
  mutate(Age = ifelse(age == "M48","4yo","6yo"))%>%
  mutate(phase = ifelse(phase == "test", "Test", "Control"))%>%
  mutate(phase= as.factor(phase))


gram_data <- read.csv(file="data/pt2_data.csv")%>%
  mutate(Age = ifelse(age == "6","6yo","8yo"))
```


# Ges

```{r}
d1.p <- d1 %>%  
  filter(block == "Uptake") %>%
  mutate(prompts = ifelse(prompts > 0,1,0)) %>%
  mutate(Age = ifelse(age == "M48","4yo","6yo")) %>%
  filter(blocktrial<5) %>%
  group_by(Age, blocktrial) %>%
  summarise(prompts = sum(prompts)) %>%
  mutate(prompts = 12 - prompts)#%>%
  #ungroup()%>%
  #add_row(Age = "3yo", blocktrial = 2, prompts = -1)


plot1 <- ggplot(d1.p, 
       aes(x = blocktrial, y = prompts, col = Age)) +
  geom_line(aes(group= Age), size = 2)+
  geom_point(aes(group= Age), size = 4)+
  theme_few() + 
  guides(col = F)+
  scale_y_continuous(name = "Spontaneous Gestures", limits = c(0,12), breaks = c(0,2,4,6,8,10,12))+
  scale_x_continuous(name = "Trial", breaks = c(1:4))+
  theme_few(base_size = 20) +
  scale_colour_solarized()
  #scale_colour_manual(name="Age",labels=c("3yo", "4yo","6yo"), values=solarized_palette(3))

d2.p <- d2 %>%
  mutate(Age = ifelse(age == "m36","3yo","4yo")) %>%
  mutate(block = relevel(block, ref = "Transfer")) %>%
  group_by(Age,trial, blocktrial,block) %>%
  summarise(prompts = sum(prompts))%>%
  mutate(prompts = 12 - prompts)%>%
  ungroup()%>%
  add_row(Age = "6yo", blocktrial = 2, prompts = -1,block = "Transfer")

plot2 <- ggplot(d2.p, 
       aes(x = blocktrial, y = prompts, col = Age)) +
  geom_line(aes(group= Age))+
  geom_point(aes(group= Age))+
  facet_grid(~block)+
  theme_few() + 
  scale_y_continuous(name =  NULL, limits = c(0,12), breaks = c(0,2,4,6,8,10,12))+
  scale_x_continuous(name = "Trial", breaks = c(1:6))+
  scale_colour_manual(name="Age",
                      labels=c("3yo", "4yo","6yo"), values=solarized_palette(3))


d3.p <- d1 %>%  
  filter(block == "Uptake") %>%
  mutate(prompts = ifelse(prompts > 0,1,0)) %>%
  mutate(Age = ifelse(age == "M48","4yo","6yo")) %>%
  filter(blocktrial<6) %>%
  group_by(Age, blocktrial) %>%
  summarise(prompts = sum(prompts))%>%
  mutate(prompts = 12 - prompts)%>%
  ungroup()%>%
  add_row(Age = "3yo", blocktrial = 2, prompts = -1)

# plot
plot3 <- ggplot(d3.p, 
       aes(x = blocktrial, y = prompts, col = Age)) +
  geom_line(aes(group= Age))+
  geom_point(aes(group= Age))+
  theme_few() + 
  scale_y_continuous(name = NULL,  limits = c(0,12), breaks = c(0,2,4,6,8,10,12))+
  scale_x_continuous(name = "Trial", breaks = c(1:5))+
   scale_colour_manual(name="Age",
                      labels=c("3yo","4yo","6yo"), values=solarized_palette(3))






```




```{r}
ggarrange(plot1, plot3,plot2, ncol = 3, nrow = 1, legend = "right", common.legend = T, widths = c(1,1,2), labels = c("A","B","C"), hjust = c(-1,0.4,0), align = "h")
```


```{r}
ggsave("plots/01_spon_prod.png", width = 6, height = 1.5, scale = 2)
```




```{r}
# summary plot paper

# spontanteous production
plot1_p <- ggplot(d1.p%>%filter(Age != "3yo"), 
       aes(x = blocktrial, y = prompts, col = Age)) +
  geom_line(aes(group= Age), size = 2)+
  geom_point(aes(group= Age), size = 4)+
  theme_few() +
  guides(col = F)+
  scale_y_continuous(name = "Spontaneous Gestures", limits = c(0,12), breaks = c(0,2,4,6,8,10,12))+
  scale_x_continuous(name = "Trial", breaks = c(1:4))+
  theme_few(base_size = 20) +
  scale_colour_manual(name="Age",
                      labels=c("4yo","6yo"), values=solarized_palette(2))


#spontaneous comprehension


d4.p2 <- read.csv(file="data/pt1_prod_up_comp.csv") %>%
  mutate(block = ifelse(block=="Uptake","Uptake","Spontaneous"))%>%
  mutate(Age = ifelse(age == "M48","4yo","6yo")) %>%
  group_by(Age, block, dyad_id)%>%
  summarise(comp = mean(comp))

d4 <- d4.p2 %>%
  group_by(Age, block, dyad_id)%>%
  summarise(comp = mean(comp)) %>%
  multi_boot_standard(col = "comp")

plot4_p <- ggplot() +
  geom_jitter(data = d4.p2, aes(x = block, y = comp, col = Age),alpha = .2, position = position_jitterdodge(jitter.width = .05, jitter.height = 0.05,
  dodge.width = 0.5))+
  geom_pointrange(data = d4,aes(x = block, y = mean, col = Age,ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .5), size = .5) +
  geom_hline(yintercept = 0.25, lty=2)+
  guides(alpha = F)+
  labs(x="Phase")+
  scale_y_continuous(name = "Comprehension", limits = c(-0.05,1.05))+
  theme_few() + 
  scale_colour_solarized()


#choosing gesture from same dyad

d6.p2 <- d6 %>%
  group_by(Age, rater)%>%
  summarise(corr = mean(corr))

d6.p3 <- d6.p2 %>%
  multi_boot_standard(col = "corr")


plot5_p <- ggplot() +
  geom_jitter(data = d6.p2, aes(x = 1, y = corr, col = Age),alpha = .2, position = position_jitterdodge(jitter.width = .15, jitter.height = 0.05, dodge.width = 0.5))+
  geom_pointrange(data = d6.p3,aes(x = 1, y = mean, col = Age,ymin = ci_lower, ymax = ci_upper),position = position_dodge(width = .5), size = .5, alpha = 1) + 
  geom_hline(yintercept = 0.5, lty=2)+
  xlab("")+
  guides(alpha = F)+
  scale_y_continuous(name = "Gesture Same Dyad", limits = c(-0.05,1.05))+
  theme_few() + 
  scale_colour_solarized()+
  theme(axis.title.x= element_blank(),axis.text.x= element_blank(), axis.ticks.x = element_blank())


# drift to arbitrary production

d7.p2 <- d7 %>%
  group_by(Age, rater)%>%
  summarise(abs = mean(abs))

d7.p3 <- d7.p2 %>%
  multi_boot_standard(col = "abs")

plot6_p <-ggplot() +
  geom_jitter(data = d7.p2, aes(x = 1, y = abs, col = Age),alpha = .2, position = position_jitterdodge(jitter.width = .15, jitter.height = 0.05,
  dodge.width = 0.5))+
  geom_pointrange(data = d7.p3,aes(x = 1, y = mean, col = Age,ymin = ci_lower, ymax = ci_upper),position = position_dodge(width = .5), size = .5, alpha = 1) + 
  geom_hline(yintercept = 0.5, lty=2)+
  xlab("")+
  guides(alpha = F)+
  scale_y_continuous(name = "Later Gesture", limits = c(-0.05,1.05))+
  theme_few() + 
  scale_colour_solarized() +
  theme(axis.title.x= element_blank(),axis.text.x= element_blank(), axis.ticks.x = element_blank())

## effort and arbitrary

d7.p5 <- d7 %>%
  group_by(Age,video,stimulus) %>%
  summarise(abs = mean(abs),
            eff = mean(effort))

plot7_p <- ggplot(data = d7.p5,aes(x = eff, y = abs, col = Age)) +
  geom_jitter(width = .015,height = .015, alpha = .2)+
  geom_smooth(method = "lm", se = T, show.legend = F)+
  geom_abline(intercept = 1, slope = -1, lty = 2, alpha = 0.5)+
  theme_few() +
  coord_fixed()+
  xlab("Effort")+
  ylab("Abstractness")+
  #stat_cor(aes(col = Age), method = "pearson", label.x = 0.25,label.y = c(0,0.1),show.legend = F)+
  scale_colour_solarized()


## drift comprehension

d8.p <- d8 %>%
  filter(condition == "Abstract")%>%
  group_by(Age, phase,id)%>%
  summarise(corr = mean(corr))

d8.p1 <- d8.p %>%
  multi_boot_standard(col = "corr")

plot8_p <- ggplot() +
  geom_jitter(data = d8.p, aes(x = phase, y = corr, col = Age), alpha = .2,position = position_jitterdodge(jitter.width = .1, jitter.height = 0.05,
  dodge.width = 0.5))+
  geom_pointrange(data = d8.p1,aes(x = phase, y = mean, col = Age,ymin = ci_lower, ymax = ci_upper),position = position_dodge(width = .5), size = .5) + 
  geom_hline(yintercept = 1/3, lty=2)+
  guides(alpha = F)+
  xlab("Phase")+
  scale_y_continuous(name = "Proportion Correct", limits = c(-0.05,1.05))+
  theme_few() + 
  scale_colour_solarized()


ggarrange(plot1_p, plot4_p,plot5_p,plot6_p,plot7_p,plot8_p, ncol = 3, nrow = 2, legend = "right", common.legend = T, labels = c("A","B","C","D","E","F"), align = "hv")

```

```{r}
ggsave("./plots/part1.png", width = 6, height = 3.5, scale = 1.5)
```

```{r, fig.width=2.5, fig.height=2}
d8.p <- d8 %>%
  filter(condition == "Abstract")%>%
  group_by(Age, phase,id)%>%
  summarise(corr = mean(corr))

d8.p1 <- d8.p %>%
  multi_boot_standard(col = "corr")

ggplot() +
  geom_jitter(data = d8.p, aes(x = phase, y = corr, col = Age), alpha = .2,position = position_jitterdodge(jitter.width = .1, jitter.height = 0.05,
  dodge.width = 0.5), size = 3)+
  geom_pointrange(data = d8.p1,aes(x = phase, y = mean, col = Age,ymin = ci_lower, ymax = ci_upper),position = position_dodge(width = .5), size = 1.5) + 
  geom_hline(yintercept = 1/3, lty=2)+
  guides(alpha = F, col = F)+
  xlab("Phase")+
  scale_y_continuous(name = "Proportion Correct", limits = c(-0.05,1.05))+
  theme_few(base_size = 20) + 
  scale_colour_solarized()




ggplot() +
  geom_jitter(data = d7.p2, aes(x = 1, y = abs, col = Age),alpha = .2, position = position_jitterdodge(jitter.width = .15, jitter.height = 0.05, dodge.width = 0.5), size = 3)+
  geom_pointrange(data = d7.p3,aes(x = 1, y = mean, col = Age,ymin = ci_lower, ymax = ci_upper),position = position_dodge(width = .5), size = 1.5, alpha = 1) + 
  geom_hline(yintercept = 0.5, lty=2)+
  xlab("")+
  guides(alpha = F, col = F)+
  scale_y_continuous(name = "Later Gesture", limits = c(-0.05,1.05))+
  theme_few(base_size = 20) + 
  scale_colour_solarized()+
  theme(axis.title.x= element_blank(),axis.text.x= element_blank(), axis.ticks.x = element_blank())

```



# Gram 


```{r}
# Gesture differentiation across conditions
gram_plot_diff_1 <- gram_data %>%
  filter(predicate != "small",
         predicate != "static",
         predicate != "one")%>%
  group_by(Age,condition,id)%>%
  summarise(diff = mean(diff=="yes"))

gram_plot_diff_2 <- gram_plot_diff_1 %>%
  group_by(Age,condition)%>%
  multi_boot_standard(col = "diff")



ggplot() +
  geom_jitter(data = gram_plot_diff_1, aes(x = condition, y = diff, col = Age, alpha = .2), position = position_jitterdodge(jitter.width = .2, jitter.height = 0.05,dodge.width = 0.5))+
  geom_pointrange(data = gram_plot_diff_2,aes(x = condition, y = mean, col = Age,ymin = ci_lower, ymax = ci_upper),position = position_dodge(width = .5), size = 0.7) +
  guides(alpha = F, color = F)+
  scale_y_continuous(name = "Proportion differentiated", limits = c(-0.05,1.05))+
  xlab("")+
  #ggtitle("Gesture differentiation by condition")+
  theme_few(base_size = 20) +
  scale_colour_manual(name="Age",
                      labels=c("6yo","8yo"), values=c("#268bd2","#b58900"))

```


```{r}
# Gesture comprehension across conditions
gram_plot_compr_1 <- gram_data %>%
  group_by(Age,condition,id)%>%
  summarise(compr = mean(compr))

gram_plot_compr_2 <- gram_plot_compr_1 %>%
  group_by(Age,condition)%>%
  multi_boot_standard(col = "compr")



ggplot() +
  geom_jitter(data = gram_plot_compr_1, aes(x = condition, y = compr, col = Age, alpha = .2), position = position_jitterdodge(jitter.width = .2, jitter.height = 0.05,dodge.width = 0.5))+
  geom_pointrange(data = gram_plot_compr_2,aes(x = condition, y = mean, col = Age,ymin = ci_lower, ymax = ci_upper),position = position_dodge(width = .5), size = 0.7) +
  guides(alpha = F, color = F)+
  scale_y_continuous(name = "Proportion correct", limits = c(-0.05,1.05))+
  xlab("")+
  #ggtitle("Gesture comprehension by condition")+
   theme_few(base_size = 20) +
  scale_colour_manual(name="Age",
                      labels=c("6yo","8yo"), values=c("#268bd2","#b58900"))

```

```{r}

# Does diff help? select only modified versions
gram_plot_compr_3 <- gram_data %>%
  filter(
         predicate != "small",
         predicate != "static",
         predicate != "one")%>%
  group_by(Age,diff,id)%>%
  summarise(compr = mean(compr))
  
gram_plot_compr_3_2 <- gram_plot_compr_3 %>%  
  multi_boot_standard(col = "compr")

ggplot() +
  geom_jitter(data = gram_plot_compr_3, aes(x = diff, y = compr, col = Age, alpha = .2), position = position_jitterdodge(jitter.width = .2, jitter.height = 0.05,dodge.width = 0.5))+
  geom_pointrange(data = gram_plot_compr_3_2,aes(x = diff, y = mean, col = Age,ymin = ci_lower, ymax = ci_upper),position = position_dodge(width = .5), size = 0.7) +
  guides(alpha = F, color = F)+
  #facet_grid(~condition)+
  scale_y_continuous(name = "Proportion correct", limits = c(-0.05,1.05))+
  xlab("Differentiate")+
  #ggtitle("Gesture comprehension by differentiation")+
  theme_few(base_size = 20) +
  scale_colour_manual(name="Age",
                      labels=c("6yo","8yo"), values=c("#268bd2","#b58900"))

```

```{r}

# number of elements (for the elaborated)only for elaborated versions) and when differentiated

gram_plot_compr_4 <- gram_data %>%
  filter(Age == "8yo",
         diff == "yes",
         predicate != "small",
         predicate != "static",
         predicate != "one")%>%
  group_by(age,condition,id)%>%
  summarise(nr_elements = mean(nr_elements))

gram_plot_compr_5 <- gram_plot_compr_4 %>%
  group_by(age,condition)%>%
  multi_boot_standard(col = "nr_elements")

ggplot() +
  geom_jitter(data = gram_plot_compr_4, aes(x = condition, y = nr_elements, col = age), alpha = .5, width = .1,height = .05)+
  geom_pointrange(data = gram_plot_compr_5,aes(x = condition, y = mean, col = age,ymin = ci_lower, ymax = ci_upper),position = position_dodge(width = .5), size = 0.7) +
  guides(alpha = F)+
  scale_y_continuous(name = "Number of meaningful elements", limits = c(0.95,3.05))+
  xlab("Condition")+
  ggtitle("Nr. of elements by condition")+
  theme_few() +
  scale_colour_solarized() 
```

```{r}

# proportion atomistic gestures

gram_plot_compr_6 <- gram_data %>%
   filter(diff == "yes",
        predicate != "small",
         predicate != "static",
         predicate != "one")%>%
  group_by(Age,condition,id)%>%
  summarise(atom = mean(hol_or_atom))




gram_plot_compr_7 <- gram_plot_compr_6 %>%
  group_by(Age,condition)%>%
  multi_boot_standard(col = "atom")

ggplot() +
  geom_jitter(data = gram_plot_compr_6, aes(x = condition, y = atom, col = Age, alpha = .2), width = .1,height = .05)+
  geom_pointrange(data = gram_plot_compr_7,aes(x = condition, y = mean, col = Age,ymin = ci_lower, ymax = ci_upper),position = position_dodge(width = .5), size = 0.7) +
  guides(alpha = F, col = F)+
  scale_y_continuous(name = "Proportion Combinatorial", limits = c(-0.05,1.05))+
  xlab("")+
  #ggtitle("Combinatorial solutions by condition")+
  theme_few(base_size = 20) +
  scale_colour_manual(name="Age",
                      labels=c("6yo","8yo"), values=c("#268bd2","#b58900"))

```

```{r}

# word order

gram_plot_compr_8 <- gram_data %>%
  filter(hol_or_atom == 1)%>%
  mutate(lang_con_order = ifelse(order == "ps" | order == "so" | order == "spo", 1,0))%>%
  group_by(condition,id)%>%
  summarise(mean = mean(lang_con_order))

gram_plot_compr_9 <- gram_plot_compr_8 %>%
  group_by(condition)%>%
  multi_boot_standard(col = "mean")

ggplot() +
  geom_jitter(data = gram_plot_compr_8, aes(x = condition, y = mean, col = condition,  alpha = .2), width = .2,height = .0)+
  geom_pointrange(data = gram_plot_compr_9,aes(x = condition, y = mean,col = condition, ymin = ci_lower, ymax = ci_upper),position = position_dodge(width = .5), size = 0.7) +
  guides(alpha = F, col = F)+
  scale_y_continuous(name = "Proportion German word order", limits = c(-0.05,1.05))+
  xlab("")+
  #ggtitle("Word order in comparison to first language")+
  theme_few(base_size = 20) +
  scale_colour_solarized() 

```


```{r}

gram_plot_10 <- gram_data %>%
  filter(compr == 1, 
         diff == "yes",
         predicate != "small",
         predicate != "static",
         predicate != "one") %>%
  group_by(condition,id)%>%
  summarise(diff_var = length(unique(typediff_1)))

gram_plot_11 <- gram_plot_10 %>%
  group_by(condition)%>%
  multi_boot_standard(col = "diff_var")

ggplot() +
  geom_jitter(data = gram_plot_10, aes(x = condition, y = diff_var, col = condition,  alpha = .2), width = .2,height = .0)+
  geom_pointrange(data = gram_plot_11,aes(x = condition, y = mean,col = condition, ymin = ci_lower, ymax = ci_upper),position = position_dodge(width = .5), size = 0.7) +
  guides(alpha = F, col = F)+
  scale_y_continuous(name = "Number of gesture types")+
  xlab("")+
  #ggtitle("Variability of gesture types within subject")+
  theme_few(base_size = 20) +
  scale_colour_solarized() 



```

```{r, fig.width=4}

gram_plot_12 <- gram_data%>%
  filter(compr == 1, 
         diff == "yes",
         predicate != "small",
         predicate != "static",
         predicate != "one")%>%
  mutate(typediff_1 = gsub("hol","enact",typediff_1),
         typediff_1 = gsub("sizeact","enact",typediff_1),
         typediff_1 = gsub("partseq","combinatorial_part",typediff_1),
         typediff_1 = plyr::mapvalues(typediff_1,c("numges","sizeges","moveges","seq"),rep("combinatorial",4)))%>%
  group_by(condition, typediff_1)%>%
  summarise(count = n())%>% 
  mutate(perc=count/sum(count))%>%
  na.omit()


ggplot() +
  geom_bar(data = na.omit(gram_plot_12), stat = "identity" ,aes(x = condition, y = perc, fill = factor(typediff_1)), width = 0.6)+
  guides(alpha = F, col = F)+
  scale_y_continuous(name = "Proportion gesture type")+
  xlab("")+
  #ggtitle("Gesture types within each condition")+
  scale_fill_pander(name = "Gesture Type")+
  theme_few(base_size = 15)



```


```{r}
# efficiency

gram_plot_compr_13 <- gram_data %>%
   filter(diff == "yes",
          condition != "transitive_2",
          condition != "transitive_3")%>%
    mutate(typediff_1 = gsub("hol","enact",typediff_1),
         typediff_1 = gsub("sizeact","enact",typediff_1),
         typediff_1 = gsub("partseq","comb_part",typediff_1),
         typediff_1 = plyr::mapvalues(typediff_1,c("numges","sizeges","moveges","seq"),rep("comb",4)))%>%
  group_by(Age,condition,agent,id)%>%
  summarise(sel = "comb" %in% typediff_1,
            prop_diff = 1- mean(is.na(typediff_1)))%>%
  filter(sel == TRUE)%>%
  group_by(Age,condition,id)%>%
  summarise(diff_eff = mean(prop_diff))

gram_plot_compr_14 <- gram_plot_compr_13 %>%
  multi_boot_standard(col = "diff_eff")

ggplot() +
  geom_jitter(data = gram_plot_compr_13, aes(x = condition, y = diff_eff, col = Age, alpha = .2), position = position_jitterdodge(jitter.width = .2, jitter.height = 0.05,dodge.width = 0.5))+
  geom_pointrange(data = gram_plot_compr_14,aes(x = condition, y = mean, col = Age,ymin = ci_lower, ymax = ci_upper),position = position_dodge(width = .5), size = 0.7) +
  guides(alpha = F, col = F)+
  scale_y_continuous(name = "Marked Gestures", limits = c(-0.05,1.05))+
  xlab("")+
  #ggtitle("Differentiation Efficiency")+
  theme_few(base_size = 20) +
  scale_colour_manual(name="Age",
                      labels=c("6yo","8yo"), values=c("#268bd2","#b58900"))

```



```{r}
hcp1 <- gram_data  %>%
  filter(typediff_1 != "NA",
         condition != "transitive_3",
         predicate != "small",
         predicate != "static",
         predicate != "one")%>%
  mutate(block = relevel(factor(block), ref = "variations"),
         typediff_1 = plyr::mapvalues(typediff_1,c("numges","sizeges","moveges","partseq", "seq"),rep("combinatorial",5)),
         typediff_1 = factor(ifelse(typediff_1 == "combinatorial", "combinatorial", "holistic")),
         typediff_1 = relevel(typediff_1, ref = "holistic"))%>%
  group_by(Age,typediff_1,id)%>%
  summarise(compr = mean(compr))
  
hcp2 <- hcp1 %>%  
  multi_boot_standard(col = "compr")

ggplot() +
  geom_jitter(data = hcp1, aes(x = typediff_1, y = compr, col = Age), position = position_jitterdodge(jitter.width = .2, jitter.height = 0.01,dodge.width = 0.5), alpha = .5)+
  geom_pointrange(data = hcp2,aes(x = typediff_1, y = mean, col = Age,ymin = ci_lower, ymax = ci_upper),position = position_dodge(width = .5), size = 0.7) +
  #facet_wrap(~condition, nrow = 1)+
  guides(alpha = F, col = F)+
  scale_y_continuous(name = "Comprehension", limits = c(-0.05,1.05))+
  xlab("")+
  #ggtitle("Comprehension")+
  theme_few(base_size = 20) +
  scale_colour_manual(name="Age",
                      labels=c("6yo","8yo"), values=c("#268bd2","#b58900"))


```


```{r}

# word order

gram_plot_compr_8 <- worder_data%>%
  group_by(condition, Age,id)%>%
  summarise(mean = mean(lang_con_order))

gram_plot_compr_9 <- gram_plot_compr_8 %>%
  group_by(condition,Age)%>%
  multi_boot_standard(col = "mean")

ggplot() +
  geom_jitter(data = gram_plot_compr_8, aes(x = Age, y = mean, col = Age,  alpha = .2), width = .2,height = .0)+
  geom_pointrange(data = gram_plot_compr_9,aes(x = Age, y = mean,col = Age, ymin = ci_lower, ymax = ci_upper),position = position_dodge(width = .5), size = 0.7) +
  guides(alpha = F, col = F)+
  scale_y_continuous(name = "Proportion German word order", limits = c(-0.05,1.05))+
  xlab("")+
  facet_grid(~condition)+
  #ggtitle("Word order in comparison to first language")+
  theme_few(base_size = 20) +
  scale_colour_manual(name="Age",
                      labels=c("6yo","8yo"), values=c("#268bd2","#b58900"))+
  theme(axis.title.x= element_blank(),axis.text.x= element_blank(), axis.ticks.x = element_blank())


```


